version: '3'
services:
  app:
    image: sentiment-analysis-with-flask:1.01
    container_name: sentiment-analysis-api
    build:
      context: .
      dockerfile: App/Dockerfile
    working_dir: /app
    volumes:
      - ./App/app.py:/app/app.py
      - ./App/requirements.txt:/app/requirements.txt
      - ./App/custom-model:/app/custom-model
      - ./App/static:/app/static
      - ./App/templates:/app/templates
    ports:
      - "5000:5000"
    command: gunicorn app:app --bind 0.0.0.0:5000
