version: '3'
services:
  app:
    image: sentiment-analysis-with-flask:1.01
    container_name: sentiment-analysis-api
    build:
      context: ./App
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./App:/app
      - ./App/static:/app/static
      - ./App/templates:/app/templates
    ports:
      - "5000:5000"
    command: gunicorn app:app --bind 0.0.0.0:5000
