version: '3'
services:
  app:
    build:
      context: ./App
      dockerfile: Dockerfile
      args:
        - DOWNLOAD_OPTION=--download
    ports:
      - "5000:5000"
    volumes:
      - ./App/templates:/app/templates
      - ./App/static:/app/static
      - ./App/model-builder:/app/model-builder
      - ./App/custom-model:/app/custom-model
